"""add_missing_tables

Revision ID: 3612d6d131aa
Revises: c328752906b2
Create Date: 2026-05-08 13:55:42.391254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3612d6d131aa'
down_revision: Union[str, Sequence[str], None] = 'c328752906b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_health_check',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('check_timestamp', sa.DateTime(), nullable=False),
    sa.Column('overall_status', sa.Enum('HEALTHY', 'DEGRADED', 'UNHEALTHY', name='healthstatus'), nullable=False),
    sa.Column('pending_invoice_count', sa.Integer(), nullable=False),
    sa.Column('failed_invoice_count', sa.Integer(), nullable=False),
    sa.Column('processing_backlog', sa.Integer(), nullable=False),
    sa.Column('failure_patterns', sa.JSON(), nullable=True),
    sa.Column('common_errors', sa.JSON(), nullable=True),
    sa.Column('fbr_api_status', sa.String(length=50), nullable=False),
    sa.Column('fbr_api_latency_ms', sa.Integer(), nullable=True),
    sa.Column('database_status', sa.String(length=50), nullable=False),
    sa.Column('database_latency_ms', sa.Integer(), nullable=True),
    sa.Column('agent_cpu_percent', sa.Float(), nullable=True),
    sa.Column('agent_memory_mb', sa.Integer(), nullable=True),
    sa.Column('anomalies_detected', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('agent_uptime_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_check_status', 'ai_agent_health_check', ['overall_status', 'check_timestamp'], unique=False, postgresql_using='btree', postgresql_ops={'check_timestamp': 'DESC'})
    op.create_index('idx_health_check_timestamp', 'ai_agent_health_check', ['check_timestamp'], unique=False, postgresql_using='btree', postgresql_ops={'check_timestamp': 'DESC'})
    op.create_index(op.f('ix_ai_agent_health_check_check_timestamp'), 'ai_agent_health_check', ['check_timestamp'], unique=False)
    op.create_index(op.f('ix_ai_agent_health_check_overall_status'), 'ai_agent_health_check', ['overall_status'], unique=False)
    op.create_table('excel_upload_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', name='exceluploadprocessingstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_sessions', 'excel_upload_session', ['user_id', 'processing_status', 'upload_timestamp'], unique=False)
    op.create_index(op.f('ix_excel_upload_session_processing_status'), 'excel_upload_session', ['processing_status'], unique=False)
    op.create_index(op.f('ix_excel_upload_session_upload_timestamp'), 'excel_upload_session', ['upload_timestamp'], unique=False)
    op.create_index(op.f('ix_excel_upload_session_user_id'), 'excel_upload_session', ['user_id'], unique=False)
    op.create_table('idempotency_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('invoice_id', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_cache_created_at'), 'idempotency_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_cache_expires_at'), 'idempotency_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_cache_idempotency_key'), 'idempotency_cache', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_idempotency_cache_invoice_id'), 'idempotency_cache', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_idempotency_cache_user_id'), 'idempotency_cache', ['user_id'], unique=False)
    op.create_table('transfer_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transfer_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('invoices_transferred', sa.Integer(), nullable=False),
    sa.Column('invoices_failed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('failed_invoice_ids', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_invoice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('excel_upload_session_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_data', sa.JSON(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'EXPIRED', 'VALIDATED', 'SUBMITTED', 'FAILED', 'BLOCKED', 'TRANSFERRED', 'TRANSFER_FAILED', name='automationinvoicestatus'), nullable=False),
    sa.Column('source', sa.Enum('EXCEL_UPLOAD', 'API', 'RECURRING', name='invoicesource'), nullable=False),
    sa.Column('validation_errors', sa.String(length=5000), nullable=True),
    sa.Column('fbr_response', sa.JSON(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('transfer_error', sa.String(length=2000), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['excel_upload_session_id'], ['excel_upload_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pending_scheduled', 'automation_invoice', ['status', 'scheduled_date', 'scheduled_time'], unique=False)
    op.create_index('idx_priority_processing', 'automation_invoice', ['priority', 'scheduled_date', 'scheduled_time'], unique=False)
    op.create_index('idx_retry_tracking', 'automation_invoice', ['status', 'last_retry_at', 'retry_count'], unique=False)
    op.create_index('idx_unique_invoice_per_user', 'automation_invoice', ['user_id', 'invoice_number'], unique=True)
    op.create_index(op.f('ix_automation_invoice_excel_upload_session_id'), 'automation_invoice', ['excel_upload_session_id'], unique=False)
    op.create_index(op.f('ix_automation_invoice_invoice_number'), 'automation_invoice', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_automation_invoice_scheduled_date'), 'automation_invoice', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_automation_invoice_scheduled_time'), 'automation_invoice', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_automation_invoice_source'), 'automation_invoice', ['source'], unique=False)
    op.create_index(op.f('ix_automation_invoice_status'), 'automation_invoice', ['status'], unique=False)
    op.create_index(op.f('ix_automation_invoice_user_id'), 'automation_invoice', ['user_id'], unique=False)
    op.create_table('automation_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('automation_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('VALIDATE', 'SUBMIT', 'UPDATE_EXCEL', 'RETRY', 'BLOCK', 'UNBLOCK', 'DELETE', 'DELETE_SESSION', name='automationlogaction'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', name='automationlogstatus'), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_invoice_id'], ['automation_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_log_action'), 'automation_log', ['action'], unique=False)
    op.create_index(op.f('ix_automation_log_automation_invoice_id'), 'automation_log', ['automation_invoice_id'], unique=False)
    op.create_index(op.f('ix_automation_log_timestamp'), 'automation_log', ['timestamp'], unique=False)
    op.alter_column('daily_posting_counters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_posting_counters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('daily_posting_counters_user_id_date_key'), 'daily_posting_counters', type_='unique')
    op.drop_index(op.f('idx_daily_counters_date'), table_name='daily_posting_counters')
    op.drop_index(op.f('idx_daily_counters_user_date'), table_name='daily_posting_counters')
    op.create_index(op.f('ix_daily_posting_counters_date'), 'daily_posting_counters', ['date'], unique=False)
    op.create_index(op.f('ix_daily_posting_counters_user_id'), 'daily_posting_counters', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_date', 'daily_posting_counters', ['user_id', 'date'])
    op.drop_index(op.f('idx_invoices_fbr_posting'), table_name='invoices')
    op.alter_column('posting_logs', 'error_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('posting_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_posting_logs_created'), table_name='posting_logs')
    op.drop_index(op.f('idx_posting_logs_invoice'), table_name='posting_logs')
    op.drop_index(op.f('idx_posting_logs_result'), table_name='posting_logs', postgresql_where="((result)::text = 'failure'::text)")
    op.drop_index(op.f('idx_posting_logs_user'), table_name='posting_logs')
    op.create_index(op.f('ix_posting_logs_created_at'), 'posting_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_posting_logs_invoice_id'), 'posting_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_posting_logs_user_id'), 'posting_logs', ['user_id'], unique=False)
    op.alter_column('user_saved_hs_codes', 'fbr_validation_error',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_saved_hs_codes_user_id_fkey'), 'user_saved_hs_codes', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_hs_codes', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_saved_product_descriptions_user_id_fkey'), 'user_saved_product_descriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_product_descriptions', 'users', ['user_id'], ['id'])
    op.alter_column('user_saved_products', 'fbr_validation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user_saved_products', 'fbr_validation_error',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('user_saved_tax_rates_user_id_fkey'), 'user_saved_tax_rates', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_tax_rates', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('user_saved_uoms_user_id_fkey'), 'user_saved_uoms', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_uoms', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'invoice_start_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'invoice_padding',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('4'))
    op.alter_column('users', 'invoice_include_year',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_users_auto_posting'), table_name='users', postgresql_where='(auto_posting_enabled = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_auto_posting'), 'users', ['auto_posting_enabled'], unique=False, postgresql_where='(auto_posting_enabled = true)')
    op.alter_column('users', 'invoice_include_year',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'invoice_padding',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('4'))
    op.alter_column('users', 'invoice_start_number',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_constraint(None, 'user_saved_uoms', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_uoms_user_id_fkey'), 'user_saved_uoms', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_saved_tax_rates', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_tax_rates_user_id_fkey'), 'user_saved_tax_rates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_saved_products', 'fbr_validation_error',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_saved_products', 'fbr_validation_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint(None, 'user_saved_product_descriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_product_descriptions_user_id_fkey'), 'user_saved_product_descriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_saved_hs_codes', type_='foreignkey')
    op.create_foreign_key(op.f('user_saved_hs_codes_user_id_fkey'), 'user_saved_hs_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_saved_hs_codes', 'fbr_validation_error',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_posting_logs_user_id'), table_name='posting_logs')
    op.drop_index(op.f('ix_posting_logs_invoice_id'), table_name='posting_logs')
    op.drop_index(op.f('ix_posting_logs_created_at'), table_name='posting_logs')
    op.create_index(op.f('idx_posting_logs_user'), 'posting_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_posting_logs_result'), 'posting_logs', ['result'], unique=False, postgresql_where="((result)::text = 'failure'::text)")
    op.create_index(op.f('idx_posting_logs_invoice'), 'posting_logs', ['invoice_id'], unique=False)
    op.create_index(op.f('idx_posting_logs_created'), 'posting_logs', ['created_at'], unique=False)
    op.alter_column('posting_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('posting_logs', 'error_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_invoices_fbr_posting'), 'invoices', ['user_id', 'status'], unique=False)
    op.drop_constraint('uq_user_date', 'daily_posting_counters', type_='unique')
    op.drop_index(op.f('ix_daily_posting_counters_user_id'), table_name='daily_posting_counters')
    op.drop_index(op.f('ix_daily_posting_counters_date'), table_name='daily_posting_counters')
    op.create_index(op.f('idx_daily_counters_user_date'), 'daily_posting_counters', ['user_id', 'date'], unique=False)
    op.create_index(op.f('idx_daily_counters_date'), 'daily_posting_counters', ['date'], unique=False)
    op.create_unique_constraint(op.f('daily_posting_counters_user_id_date_key'), 'daily_posting_counters', ['user_id', 'date'], postgresql_nulls_not_distinct=False)
    op.alter_column('daily_posting_counters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_posting_counters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_automation_log_timestamp'), table_name='automation_log')
    op.drop_index(op.f('ix_automation_log_automation_invoice_id'), table_name='automation_log')
    op.drop_index(op.f('ix_automation_log_action'), table_name='automation_log')
    op.drop_table('automation_log')
    op.drop_index(op.f('ix_automation_invoice_user_id'), table_name='automation_invoice')
    op.drop_index(op.f('ix_automation_invoice_status'), table_name='automation_invoice')
    op.drop_index(op.f('ix_automation_invoice_source'), table_name='automation_invoice')
    op.drop_index(op.f('ix_automation_invoice_scheduled_time'), table_name='automation_invoice')
    op.drop_index(op.f('ix_automation_invoice_scheduled_date'), table_name='automation_invoice')
    op.drop_index(op.f('ix_automation_invoice_invoice_number'), table_name='automation_invoice')
    op.drop_index(op.f('ix_automation_invoice_excel_upload_session_id'), table_name='automation_invoice')
    op.drop_index('idx_unique_invoice_per_user', table_name='automation_invoice')
    op.drop_index('idx_retry_tracking', table_name='automation_invoice')
    op.drop_index('idx_priority_processing', table_name='automation_invoice')
    op.drop_index('idx_pending_scheduled', table_name='automation_invoice')
    op.drop_table('automation_invoice')
    op.drop_table('transfer_log')
    op.drop_index(op.f('ix_idempotency_cache_user_id'), table_name='idempotency_cache')
    op.drop_index(op.f('ix_idempotency_cache_invoice_id'), table_name='idempotency_cache')
    op.drop_index(op.f('ix_idempotency_cache_idempotency_key'), table_name='idempotency_cache')
    op.drop_index(op.f('ix_idempotency_cache_expires_at'), table_name='idempotency_cache')
    op.drop_index(op.f('ix_idempotency_cache_created_at'), table_name='idempotency_cache')
    op.drop_table('idempotency_cache')
    op.drop_index(op.f('ix_excel_upload_session_user_id'), table_name='excel_upload_session')
    op.drop_index(op.f('ix_excel_upload_session_upload_timestamp'), table_name='excel_upload_session')
    op.drop_index(op.f('ix_excel_upload_session_processing_status'), table_name='excel_upload_session')
    op.drop_index('idx_user_sessions', table_name='excel_upload_session')
    op.drop_table('excel_upload_session')
    op.drop_index(op.f('ix_ai_agent_health_check_overall_status'), table_name='ai_agent_health_check')
    op.drop_index(op.f('ix_ai_agent_health_check_check_timestamp'), table_name='ai_agent_health_check')
    op.drop_index('idx_health_check_timestamp', table_name='ai_agent_health_check', postgresql_using='btree', postgresql_ops={'check_timestamp': 'DESC'})
    op.drop_index('idx_health_check_status', table_name='ai_agent_health_check', postgresql_using='btree', postgresql_ops={'check_timestamp': 'DESC'})
    op.drop_table('ai_agent_health_check')
    # ### end Alembic commands ###
