"""Add daily posting counter table

Revision ID: ff92d41609c2
Revises: 5d49bbe6cf4f
Create Date: 2026-05-09 11:59:01.324715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff92d41609c2'
down_revision: Union[str, Sequence[str], None] = '5d49bbe6cf4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbr_sro_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fbr_sro_items_code'), 'fbr_sro_items', ['code'], unique=True)
    op.create_table('fbr_sync_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_log_status', 'fbr_sync_logs', ['sync_type', 'status', 'started_at'], unique=False)
    op.create_table('daily_posting_counters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('posted_count', sa.Integer(), nullable=False),
    sa.Column('window_start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_index(op.f('ix_daily_posting_counters_date'), 'daily_posting_counters', ['date'], unique=False)
    op.create_index(op.f('ix_daily_posting_counters_user_id'), 'daily_posting_counters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_posting_counters_user_id'), table_name='daily_posting_counters')
    op.drop_index(op.f('ix_daily_posting_counters_date'), table_name='daily_posting_counters')
    op.drop_table('daily_posting_counters')
    op.drop_index('idx_sync_log_status', table_name='fbr_sync_logs')
    op.drop_table('fbr_sync_logs')
    op.drop_index(op.f('ix_fbr_sro_items_code'), table_name='fbr_sro_items')
    op.drop_table('fbr_sro_items')
    # ### end Alembic commands ###
